# -*- coding: utf-8 -*-
"""The shipped files under dist/ (rule 66, rule 16): the eleven translation files for every TR key in src/Page.cpp,
and the INI with the compiled defaults.

    python tools/gen-dist.py

Keys the Skyrim HUD Position Manager already carries with the same meaning are taken from its eleven files
(6. current wip mods/HUDPositionManager/dist/Interface/Translations); the keys new to the remaster port, or whose
English changed, are in NEW below. The script fails loudly when a key used in the code has no text in a language."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SKYRIM = r"D:\Claude output\6. current wip mods\HUDPositionManager\dist\Interface\Translations"
OUT = os.path.join(REPO, r"dist\OblivionRemastered\Binaries\Win64\OBSE\Plugins\ApocryphaMenuFramework\Translations")
LANGS = ["english", "japanese", "korean", "chinese", "russian", "german", "french", "spanish", "italian", "polish", "czech"]

REUSE = {"HPM_Intro", "HPM_Enabled", "HPM_NoHud", "HPM_MoveX", "HPM_MoveY", "HPM_Size", "HPM_Hide", "HPM_ResetOne", "HPM_ResetAll",
         "HPM_El_Health", "HPM_El_Magicka", "HPM_El_Compass", "HPM_El_Crosshair", "HPM_El_EnemyHealth", "HPM_MoveWith",
         "HPM_MoveWithNone", "HPM_LinkBars"}

# key -> [english, japanese, korean, chinese, russian, german, french, spanish, italian, polish, czech]
NEW = {
    "HPM_EnabledHint": [
        "Off: every element goes back to where the game puts it.",
        "オフ: すべての要素がゲーム本来の位置に戻ります。",
        "끄면 모든 요소가 게임이 정한 위치로 돌아갑니다.",
        "关闭：每个元素都回到游戏默认的位置。",
        "Выкл.: каждый элемент возвращается туда, где его размещает игра.",
        "Aus: jedes Element kehrt dorthin zurück, wo das Spiel es platziert.",
        "Désactivé : chaque élément revient là où le jeu le place.",
        "Desactivado: cada elemento vuelve a donde lo coloca el juego.",
        "Disattivato: ogni elemento torna dove lo colloca il gioco.",
        "Wyłączone: każdy element wraca tam, gdzie umieszcza go gra.",
        "Vypnuto: každý prvek se vrátí tam, kam ho umisťuje hra.",
    ],
    "HPM_NotFound": [
        "Not in your HUD right now: it may appear later, or the HUD you use may not have it. Its settings are kept.",
        "現在HUDにありません。後で表示されるか、使用中のHUDには存在しない可能性があります。設定は保持されます。",
        "지금 HUD에 없습니다. 나중에 나타나거나, 사용 중인 HUD에 없을 수 있습니다. 설정은 유지됩니다.",
        "当前不在你的HUD中：它可能稍后出现，或你使用的HUD没有它。其设置会保留。",
        "Сейчас его нет в вашем HUD: он может появиться позже, или в вашем HUD его нет. Настройки сохраняются.",
        "Derzeit nicht in deinem HUD: es kann später erscheinen, oder dein HUD hat es nicht. Die Einstellungen bleiben erhalten.",
        "Absent de votre ATH pour l'instant : il peut apparaître plus tard, ou votre ATH ne l'a pas. Ses réglages sont conservés.",
        "Ahora no está en tu HUD: puede aparecer más tarde, o el HUD que usas no lo tiene. Sus ajustes se conservan.",
        "Ora non è nel tuo HUD: potrebbe comparire più tardi, o l'HUD che usi non lo ha. Le sue impostazioni sono conservate.",
        "Teraz nie ma go w twoim HUD: może pojawić się później albo używany HUD go nie ma. Ustawienia są zachowane.",
        "Teď není ve vašem HUD: může se objevit později, nebo ho váš HUD nemá. Nastavení zůstává zachováno.",
    ],
    "HPM_Found": [
        "In your HUD. Changes show at once.",
        "HUDにあります。変更はすぐに反映されます。",
        "HUD에 있습니다. 변경 사항이 바로 표시됩니다.",
        "在你的HUD中。更改会立即显示。",
        "Есть в вашем HUD. Изменения видны сразу.",
        "In deinem HUD. Änderungen sind sofort sichtbar.",
        "Dans votre ATH. Les changements sont visibles aussitôt.",
        "En tu HUD. Los cambios se ven al instante.",
        "Nel tuo HUD. Le modifiche si vedono subito.",
        "W twoim HUD. Zmiany widać od razu.",
        "Ve vašem HUD. Změny se projeví hned.",
    ],
    "HPM_El_Fatigue": ["Fatigue", "疲労", "피로", "疲劳", "Усталость", "Ausdauer", "Fatigue", "Fatiga", "Fatica", "Zmęczenie", "Únava"],
    "HPM_El_WeaponIcon": ["Weapon icon", "武器アイコン", "무기 아이콘", "武器图标", "Значок оружия", "Waffensymbol", "Icône d'arme", "Icono de arma", "Icona dell'arma", "Ikona broni", "Ikona zbraně"],
    "HPM_El_MagicIcon": ["Spell icon", "呪文アイコン", "주문 아이콘", "法术图标", "Значок заклинания", "Zaubersymbol", "Icône de sort", "Icono de hechizo", "Icona dell'incantesimo", "Ikona zaklęcia", "Ikona kouzla"],
    "HPM_El_EffectIcons": ["Active effects", "有効な効果", "활성 효과", "生效效果", "Активные эффекты", "Aktive Effekte", "Effets actifs", "Efectos activos", "Effetti attivi", "Aktywne efekty", "Aktivní efekty"],
    "HPM_El_SneakEye": ["Sneak eye", "隠密の目", "은신 눈", "潜行之眼", "Глаз скрытности", "Schleichauge", "Œil de furtivité", "Ojo de sigilo", "Occhio furtivo", "Oko skradania", "Oko plížení"],
    "HPM_El_LevelUp": ["Level-up gauge", "レベルアップゲージ", "레벨 업 게이지", "升级计量条", "Индикатор уровня", "Aufstiegsanzeige", "Jauge de niveau", "Indicador de nivel", "Indicatore di livello", "Wskaźnik awansu", "Ukazatel postupu"],
    "HPM_El_Info": ["Target name and value", "対象の名前と価値", "대상 이름과 가치", "目标名称与价值", "Имя и цена цели", "Name und Wert des Ziels", "Nom et valeur de la cible", "Nombre y valor del objetivo", "Nome e valore del bersaglio", "Nazwa i wartość celu", "Název a hodnota cíle"],
    "HPM_El_Subtitles": ["Subtitles and notifications", "字幕と通知", "자막과 알림", "字幕与通知", "Субтитры и уведомления", "Untertitel und Meldungen", "Sous-titres et notifications", "Subtítulos y notificaciones", "Sottotitoli e notifiche", "Napisy i powiadomienia", "Titulky a oznámení"],
    "HPM_El_Breath": ["Breath meter", "息メーター", "숨 게이지", "屏息计量条", "Индикатор дыхания", "Atemanzeige", "Jauge de souffle", "Indicador de aire", "Indicatore del respiro", "Wskaźnik oddechu", "Ukazatel dechu"],
    "HPM_El_Location": ["Location name", "場所の名前", "지역 이름", "地点名称", "Название места", "Ortsname", "Nom du lieu", "Nombre del lugar", "Nome del luogo", "Nazwa miejsca", "Název místa"],
    "HPM_El_DamageIndicators": ["Damage direction", "ダメージの方向", "피해 방향", "伤害方向", "Направление урона", "Schadensrichtung", "Direction des dégâts", "Dirección del daño", "Direzione del danno", "Kierunek obrażeń", "Směr poškození"],
    "HPM_El_Notifications": ["Pop-up notifications", "ポップアップ通知", "팝업 알림", "弹出通知", "Всплывающие уведомления", "Einblendmeldungen", "Notifications contextuelles", "Notificaciones emergentes", "Notifiche a comparsa", "Powiadomienia wyskakujące", "Vyskakovací oznámení"],
    "HPM_El_Tutorial": ["Tutorial messages", "チュートリアルメッセージ", "튜토리얼 메시지", "教程提示", "Сообщения обучения", "Tutorial-Meldungen", "Messages du tutoriel", "Mensajes del tutorial", "Messaggi del tutorial", "Komunikaty samouczka", "Zprávy výuky"],
    "HPM_AlwaysOne": ["Always visible", "常に表示", "항상 표시", "始终显示", "Всегда видно", "Immer sichtbar", "Toujours visible", "Siempre visible", "Sempre visibile", "Zawsze widoczne", "Vždy viditelné"],
    "HPM_AlwaysOneHint": [
        "The game fades this out on its own. On: it stays shown while you play.",
        "ゲームはこれを自動で薄くします。オン: プレイ中は表示されたままになります。",
        "게임이 이것을 스스로 흐리게 합니다. 켜면 플레이 중에 계속 표시됩니다.",
        "游戏会自行将其淡出。开启：游戏中保持显示。",
        "Игра сама плавно скрывает это. Вкл.: остаётся видимым во время игры.",
        "Das Spiel blendet es von selbst aus. An: es bleibt beim Spielen sichtbar.",
        "Le jeu l'estompe de lui-même. Activé : il reste affiché pendant le jeu.",
        "El juego lo atenúa por sí solo. Activado: permanece visible mientras juegas.",
        "Il gioco lo dissolve da solo. Attivato: resta visibile mentre giochi.",
        "Gra sama go wygasza. Włączone: pozostaje widoczny podczas gry.",
        "Hra ho sama nechá zmizet. Zapnuto: zůstane zobrazený během hry.",
    ],
    "HPM_LinkedHint": [
        "Moves with Health while \"Move the three bars together\" is on.",
        "「3つのバーを一緒に動かす」がオンの間は体力と一緒に動きます。",
        "\"세 막대를 함께 이동\"이 켜져 있는 동안 체력과 함께 움직입니다.",
        "开启“三条栏一起移动”时随生命值一起移动。",
        "Движется вместе со здоровьем, пока включено «Двигать три полосы вместе».",
        "Bewegt sich mit der Gesundheit, solange „Die drei Leisten zusammen bewegen“ an ist.",
        "Se déplace avec la santé tant que « Déplacer les trois barres ensemble » est activé.",
        "Se mueve con la salud mientras \"Mover las tres barras juntas\" está activado.",
        "Si muove con la salute finché \"Sposta le tre barre insieme\" è attivo.",
        "Porusza się razem ze zdrowiem, gdy włączone jest „Przesuwaj trzy paski razem”.",
        "Pohybuje se se zdravím, dokud je zapnuto „Posouvat tři lišty společně“.",
    ],
    "HPM_LinkBarsHint": [
        "Magicka and Fatigue move with Health.",
        "マジカと疲労は体力と一緒に動きます。",
        "매지카와 피로가 체력과 함께 움직입니다.",
        "魔力与疲劳随生命值一起移动。",
        "Магия и усталость движутся вместе со здоровьем.",
        "Magicka und Ausdauer bewegen sich mit der Gesundheit.",
        "La magie et la fatigue se déplacent avec la santé.",
        "La magia y la fatiga se mueven con la salud.",
        "Magicka e fatica si muovono con la salute.",
        "Magia i zmęczenie poruszają się razem ze zdrowiem.",
        "Magie a únava se pohybují se zdravím.",
    ],
    "HPM_GroupVisibility": ["HUD visibility", "HUDの表示", "HUD 표시", "HUD显示", "Видимость HUD", "HUD-Sichtbarkeit", "Visibilité de l'ATH", "Visibilidad del HUD", "Visibilità dell'HUD", "Widoczność HUD", "Viditelnost HUD"],
    "HPM_AlwaysAll": ["Always visible", "常に表示", "항상 표시", "始终显示", "Всегда видно", "Immer sichtbar", "Toujours visible", "Siempre visible", "Sempre visibile", "Zawsze widoczne", "Vždy viditelné"],
    "HPM_AlwaysAllOnHint": [
        "The bars stay shown while you play. Menus, dialogue and loading screens still hide the HUD.",
        "プレイ中はバーが表示されたままになります。メニュー、会話、ロード画面ではHUDは引き続き隠れます。",
        "플레이 중에는 막대가 계속 표시됩니다. 메뉴, 대화, 로딩 화면에서는 HUD가 여전히 숨겨집니다.",
        "游戏中各栏保持显示。菜单、对话和加载画面仍会隐藏HUD。",
        "Полосы остаются видимыми во время игры. В меню, диалогах и на экранах загрузки HUD по-прежнему скрыт.",
        "Die Leisten bleiben beim Spielen sichtbar. Menüs, Gespräche und Ladebildschirme blenden das HUD weiterhin aus.",
        "Les barres restent affichées pendant le jeu. Les menus, les dialogues et les écrans de chargement masquent toujours l'ATH.",
        "Las barras permanecen visibles mientras juegas. Los menús, los diálogos y las pantallas de carga siguen ocultando el HUD.",
        "Le barre restano visibili mentre giochi. Menu, dialoghi e schermate di caricamento nascondono comunque l'HUD.",
        "Paski pozostają widoczne podczas gry. Menu, dialogi i ekrany ładowania nadal ukrywają HUD.",
        "Lišty zůstávají zobrazené během hry. Nabídky, dialogy a načítací obrazovky HUD nadále skrývají.",
    ],
    "HPM_AlwaysAllOffHint": [
        "Off: the game decides. The bars fade out when they are full.",
        "オフ: ゲームが決めます。バーは満タンになると薄くなります。",
        "끄면 게임이 결정합니다. 막대는 가득 차면 흐려집니다.",
        "关闭：由游戏决定。各栏满时会淡出。",
        "Выкл.: решает игра. Полосы плавно исчезают, когда заполнены.",
        "Aus: das Spiel entscheidet. Die Leisten blenden aus, wenn sie voll sind.",
        "Désactivé : le jeu décide. Les barres s'estompent quand elles sont pleines.",
        "Desactivado: decide el juego. Las barras se atenúan cuando están llenas.",
        "Disattivato: decide il gioco. Le barre si dissolvono quando sono piene.",
        "Wyłączone: decyduje gra. Paski gasną, gdy są pełne.",
        "Vypnuto: rozhoduje hra. Lišty zmizí, když jsou plné.",
    ],
    # the Presets tab (2026-09-29)
    "HPM_TabPresets": [
        "Presets",
        "プリセット",
        "프리셋",
        "预设",
        "Пресеты",
        "Voreinstellungen",
        "Préréglages",
        "Ajustes predefinidos",
        "Preimpostazioni",
        "Ustawienia wstępne",
        "Předvolby",
    ],
    "HPM_TabLayout": [
        "Layout",
        "レイアウト",
        "레이아웃",
        "布局",
        "Расположение",
        "Layout",
        "Disposition",
        "Diseño",
        "Disposizione",
        "Układ",
        "Rozložení",
    ],
    "HPM_PresetsIntro": [
        "A preset is a whole layout: every element's position, size and visibility. Load one made by someone else, or save your own to switch between.",
        "プリセットはレイアウト全体です: 各要素の位置、大きさ、表示。他の人が作ったものを読み込むか、自分のものを保存して切り替えられます。",
        "프리셋은 레이아웃 전체입니다: 각 요소의 위치, 크기, 표시 여부. 다른 사람이 만든 것을 불러오거나, 자신의 것을 저장해 전환할 수 있습니다.",
        "预设是完整的布局：每个元素的位置、大小和显示。载入他人制作的预设，或保存自己的预设以便切换。",
        "Пресет — это вся компоновка: положение, размер и видимость каждого элемента. Загрузите чужой или сохраните свои, чтобы переключаться между ними.",
        "Eine Voreinstellung ist ein ganzes Layout: Position, Größe und Sichtbarkeit jedes Elements. Lade eine von jemand anderem oder speichere deine eigenen, um zwischen ihnen zu wechseln.",
        "Un préréglage est une disposition complète : position, taille et visibilité de chaque élément. Chargez-en un fait par quelqu'un d'autre, ou enregistrez les vôtres pour passer de l'un à l'autre.",
        "Un ajuste predefinido es un diseño completo: posición, tamaño y visibilidad de cada elemento. Carga uno hecho por otra persona o guarda los tuyos para cambiar entre ellos.",
        "Una preimpostazione è una disposizione completa: posizione, dimensione e visibilità di ogni elemento. Caricane una fatta da altri, o salva le tue per passare dall'una all'altra.",
        "Ustawienie wstępne to cały układ: pozycja, rozmiar i widoczność każdego elementu. Wczytaj czyjeś albo zapisz własne, aby się między nimi przełączać.",
        "Předvolba je celé rozložení: poloha, velikost a viditelnost každého prvku. Načtěte cizí, nebo si uložte vlastní a přepínejte mezi nimi.",
    ],
    "HPM_PresetsNone": [
        "No presets yet. Save your layout below, or put a preset file from another author in the folder above.",
        "プリセットはまだありません。下でレイアウトを保存するか、他の作者のプリセットファイルを上のフォルダーに入れてください。",
        "아직 프리셋이 없습니다. 아래에서 레이아웃을 저장하거나, 다른 제작자의 프리셋 파일을 위 폴더에 넣으세요.",
        "还没有预设。在下方保存你的布局，或将其他作者的预设文件放入上面的文件夹。",
        "Пресетов пока нет. Сохраните свою компоновку ниже или положите файл пресета другого автора в папку выше.",
        "Noch keine Voreinstellungen. Speichere unten dein Layout oder lege die Voreinstellungsdatei eines anderen Autors in den Ordner oben.",
        "Aucun préréglage pour l'instant. Enregistrez votre disposition ci-dessous, ou placez le fichier de préréglage d'un autre auteur dans le dossier ci-dessus.",
        "Aún no hay ajustes predefinidos. Guarda tu diseño abajo o coloca el archivo de otro autor en la carpeta de arriba.",
        "Nessuna preimpostazione ancora. Salva la tua disposizione qui sotto, o metti il file di un altro autore nella cartella qui sopra.",
        "Brak ustawień wstępnych. Zapisz swój układ poniżej albo umieść plik innego autora w folderze powyżej.",
        "Zatím žádné předvolby. Uložte své rozložení níže, nebo vložte soubor předvolby jiného autora do složky výše.",
    ],
    "HPM_Preset": [
        "Preset",
        "プリセット",
        "프리셋",
        "预设",
        "Пресет",
        "Voreinstellung",
        "Préréglage",
        "Ajuste predefinido",
        "Preimpostazione",
        "Ustawienie wstępne",
        "Předvolba",
    ],
    "HPM_PresetLoad": [
        "Load this preset",
        "このプリセットを読み込む",
        "이 프리셋 불러오기",
        "载入此预设",
        "Загрузить этот пресет",
        "Diese Voreinstellung laden",
        "Charger ce préréglage",
        "Cargar este ajuste",
        "Carica questa preimpostazione",
        "Wczytaj to ustawienie",
        "Načíst tuto předvolbu",
    ],
    "HPM_PresetLoaded": [
        "Loaded",
        "読み込みました",
        "불러왔습니다",
        "已载入",
        "Загружено",
        "Geladen",
        "Chargé",
        "Cargado",
        "Caricata",
        "Wczytano",
        "Načteno",
    ],
    "HPM_PresetFailed": [
        "Could not read",
        "読み込めませんでした",
        "읽을 수 없습니다",
        "无法读取",
        "Не удалось прочитать",
        "Konnte nicht gelesen werden",
        "Lecture impossible",
        "No se pudo leer",
        "Impossibile leggere",
        "Nie można odczytać",
        "Nelze přečíst",
    ],
    "HPM_PresetDelete": [
        "Delete",
        "削除",
        "삭제",
        "删除",
        "Удалить",
        "Löschen",
        "Supprimer",
        "Eliminar",
        "Elimina",
        "Usuń",
        "Smazat",
    ],
    "HPM_PresetDeleteSure": [
        "Press again to delete",
        "もう一度押すと削除します",
        "다시 누르면 삭제됩니다",
        "再按一次以删除",
        "Нажмите ещё раз, чтобы удалить",
        "Zum Löschen erneut drücken",
        "Appuyez encore pour supprimer",
        "Pulsa de nuevo para eliminar",
        "Premi di nuovo per eliminare",
        "Naciśnij ponownie, aby usunąć",
        "Stiskněte znovu pro smazání",
    ],
    "HPM_PresetDeleted": [
        "Deleted",
        "削除しました",
        "삭제했습니다",
        "已删除",
        "Удалено",
        "Gelöscht",
        "Supprimé",
        "Eliminado",
        "Eliminata",
        "Usunięto",
        "Smazáno",
    ],
    "HPM_PresetDeleteFailed": [
        "Could not delete",
        "削除できませんでした",
        "삭제할 수 없습니다",
        "无法删除",
        "Не удалось удалить",
        "Konnte nicht gelöscht werden",
        "Suppression impossible",
        "No se pudo eliminar",
        "Impossibile eliminare",
        "Nie można usunąć",
        "Nelze smazat",
    ],
    "HPM_PresetSaveGroup": [
        "Save my layout",
        "自分のレイアウトを保存",
        "내 레이아웃 저장",
        "保存我的布局",
        "Сохранить мою компоновку",
        "Mein Layout speichern",
        "Enregistrer ma disposition",
        "Guardar mi diseño",
        "Salva la mia disposizione",
        "Zapisz mój układ",
        "Uložit mé rozložení",
    ],
    "HPM_PresetName": [
        "Name",
        "名前",
        "이름",
        "名称",
        "Название",
        "Name",
        "Nom",
        "Nombre",
        "Nome",
        "Nazwa",
        "Název",
    ],
    "HPM_PresetNameHint": [
        "With a controller, leave the name as it is: each save gets its own number.",
        "コントローラーの場合は名前をそのままにしてください: 保存するたびに番号が付きます。",
        "컨트롤러를 쓴다면 이름을 그대로 두세요: 저장할 때마다 번호가 붙습니다.",
        "使用手柄时保持名称不变：每次保存都会自动编号。",
        "С геймпадом оставьте название как есть: каждое сохранение получит свой номер.",
        "Mit einem Controller lass den Namen wie er ist: jede Speicherung bekommt ihre eigene Nummer.",
        "Avec une manette, laissez le nom tel quel : chaque enregistrement reçoit son propre numéro.",
        "Con mando, deja el nombre como está: cada guardado recibe su propio número.",
        "Con un controller lascia il nome com'è: ogni salvataggio riceve il proprio numero.",
        "Z padem zostaw nazwę bez zmian: każdy zapis dostaje własny numer.",
        "S ovladačem nechte název tak, jak je: každé uložení dostane vlastní číslo.",
    ],
    "HPM_PresetSave": [
        "Save as a preset",
        "プリセットとして保存",
        "프리셋으로 저장",
        "保存为预设",
        "Сохранить как пресет",
        "Als Voreinstellung speichern",
        "Enregistrer comme préréglage",
        "Guardar como ajuste predefinido",
        "Salva come preimpostazione",
        "Zapisz jako ustawienie wstępne",
        "Uložit jako předvolbu",
    ],
    "HPM_PresetSaveFailed": [
        "The preset could not be written.",
        "プリセットを書き込めませんでした。",
        "프리셋을 쓸 수 없습니다.",
        "无法写入预设。",
        "Не удалось записать пресет.",
        "Die Voreinstellung konnte nicht geschrieben werden.",
        "Le préréglage n'a pas pu être écrit.",
        "No se pudo escribir el ajuste predefinido.",
        "Impossibile scrivere la preimpostazione.",
        "Nie udało się zapisać ustawienia wstępnego.",
        "Předvolbu se nepodařilo zapsat.",
    ],
    "HPM_PresetSaved": [
        "Saved",
        "保存しました",
        "저장했습니다",
        "已保存",
        "Сохранено",
        "Gespeichert",
        "Enregistré",
        "Guardado",
        "Salvata",
        "Zapisano",
        "Uloženo",
    ],
    "HPM_PresetSaveTo": [
        "Save to",
        "保存先",
        "저장 위치",
        "保存到",
        "Сохранить в",
        "Speichern in",
        "Enregistrer dans",
        "Guardar en",
        "Salva in",
        "Zapisz do",
        "Uložit do",
    ],
    "HPM_PresetNew": [
        "New preset",
        "新しいプリセット",
        "새 프리셋",
        "新预设",
        "Новый пресет",
        "Neue Voreinstellung",
        "Nouveau préréglage",
        "Nuevo ajuste predefinido",
        "Nuova preimpostazione",
        "Nowe ustawienie wstępne",
        "Nová předvolba",
    ],
    "HPM_PresetUpdate": [
        "Update this preset with my layout",
        "このプリセットを今のレイアウトで更新",
        "이 프리셋을 내 레이아웃으로 업데이트",
        "用我的布局更新此预设",
        "Обновить этот пресет моей компоновкой",
        "Diese Voreinstellung mit meinem Layout aktualisieren",
        "Mettre à jour ce préréglage avec ma disposition",
        "Actualizar este ajuste con mi diseño",
        "Aggiorna questa preimpostazione con la mia disposizione",
        "Zaktualizuj to ustawienie moim układem",
        "Aktualizovat tuto předvolbu mým rozložením",
    ],
    "HPM_NoOverlap": [
        "HUD widget collision",
        "HUDウィジェットの衝突",
        "HUD 위젯 충돌",
        "HUD 组件碰撞",
        "Столкновение виджетов HUD",
        "HUD-Widget-Kollision",
        "Collision des widgets du HUD",
        "Colisión de widgets del HUD",
        "Collisione dei widget dell'HUD",
        "Kolizja widżetów HUD",
        "Kolize widgetů HUD",
    ],
    "HPM_NoOverlapHint": [
        "On: a widget you move stops where its edge meets another widget's, so the bars line up without decimal-point work. Off: widgets may overlap.",
        "オン: 動かしたウィジェットは別のウィジェットの端に当たったところで止まるので、小数点まで合わせなくてもバーが揃います。オフ: ウィジェットは重なることがあります。",
        "켜면 움직이는 위젯이 다른 위젯의 가장자리에 닿는 곳에서 멈추므로 소수점까지 맞추지 않아도 막대가 정렬됩니다. 끄면 위젯이 겹칠 수 있습니다.",
        "开启：移动的组件在其边缘碰到另一组件时停止，这样各栏无需精确到小数点即可对齐。关闭：组件可以重叠。",
        "Вкл.: перемещаемый виджет останавливается там, где его край касается другого виджета, так что полосы выравниваются без подгонки до десятых. Выкл.: виджеты могут перекрываться.",
        "An: ein bewegtes Widget hält an, wo seine Kante auf die eines anderen trifft, so dass sich die Leisten ohne Kommastellen-Arbeit ausrichten. Aus: Widgets dürfen sich überlappen.",
        "Activé : un widget déplacé s'arrête là où son bord rencontre celui d'un autre, les barres s'alignent donc sans réglage à la décimale. Désactivé : les widgets peuvent se chevaucher.",
        "Activado: un widget que muevas se detiene donde su borde toca el de otro, así las barras se alinean sin ajustar decimales. Desactivado: los widgets pueden superponerse.",
        "Attivato: un widget che sposti si ferma dove il suo bordo incontra quello di un altro, così le barre si allineano senza lavorare sui decimali. Disattivato: i widget possono sovrapporsi.",
        "Włączone: przesuwany widżet zatrzymuje się tam, gdzie jego krawędź styka się z krawędzią innego, więc paski wyrównują się bez dłubania w ułamkach. Wyłączone: widżety mogą się nakładać.",
        "Zapnuto: přesouvaný widget se zastaví tam, kde se jeho okraj dotkne jiného, takže se lišty zarovnají bez ladění desetin. Vypnuto: widgety se mohou překrývat.",
    ],
    "HPM_El_QuickWheel": [
        "Quick wheel",
        "クイックホイール",
        "퀵 휠",
        "快捷轮盘",
        "Быстрое колесо",
        "Schnellrad",
        "Roue rapide",
        "Rueda rápida",
        "Ruota rapida",
        "Szybkie koło",
        "Rychlé kolo",
    ],
}


def read_translation(path):
    raw = open(path, "rb").read()
    text = raw[2:].decode("utf-16-le") if raw[:2] == b"\xff\xfe" else raw.decode("utf-8-sig")
    out = {}
    for line in text.splitlines():
        if line.startswith("$") and "\t" in line:
            k, v = line[1:].split("\t", 1)
            out[k] = v
    return out


code = open(os.path.join(REPO, "src", "Page.cpp"), encoding="utf-8").read()
used = sorted(set(re.findall(r'\bTR\s*\(\s*"([A-Za-z0-9_]+)"', code)))
english_in_code = dict(re.findall(r'\bTR\s*\(\s*"([A-Za-z0-9_]+)"\s*,\s*"((?:[^"\\]|\\.)*)"', code))
os.makedirs(OUT, exist_ok=True)
for li, lang in enumerate(LANGS):
    sky = read_translation(os.path.join(SKYRIM, "HUDPositionManager_%s.txt" % lang))
    lines = []
    for key in used:
        if key in NEW:
            text = NEW[key][li]
        elif key in REUSE and key in sky:
            text = sky[key] if lang != "english" else english_in_code.get(key, sky[key]).replace('\\"', '"')
        else:
            raise SystemExit("no %s text for %s" % (lang, key))
        lines.append("$%s\t%s" % (key, text))
    with open(os.path.join(OUT, "HUDPositionManager_%s.txt" % lang), "wb") as f:
        f.write(b"\xff\xfe" + ("\r\n".join(lines) + "\r\n").encode("utf-16-le"))
print("%d keys x %d languages -> %s" % (len(used), len(LANGS), OUT))

# the INI with the compiled defaults (Settings.h / Elements.h)
ELEMENTS = [
    ("Health", True), ("Magicka", True), ("Fatigue", True), ("Compass", False), ("Crosshair", False), ("WeaponIcon", False),
    ("MagicIcon", False), ("EffectIcons", False), ("EnemyHealth", False), ("SneakEye", False), ("LevelUp", False), ("Info", False),
    ("Subtitles", False), ("Breath", False), ("Location", False), ("DamageIndicators", False), ("Notifications", False), ("Tutorial", False), ("QuickWheel", False),
]
ini = [
    "; HUD Position Manager for Oblivion - settings. The settings page in Apocrypha Menu Framework writes this file;",
    "; edit it by hand only with the game closed. fX / fY are a percentage of the screen's width / height (the same layout",
    "; on every resolution); fScale 1.00 = the game's size.",
    "",
    "[General]",
    "; Apply my layout: 0 puts every element back where the game places it.",
    "bEnabled=1",
    "; Move the three bars together: Magicka and Fatigue move with Health.",
    "bLinkBars=1",
    "; HUD visibility: 0 = the game decides (the bars fade out when full), 1 = the bars stay shown while you play.",
    "bAlwaysVisible=0",
    "; HUD widget collision: 1 = a widget you move stops where its edge meets another widget's; 0 = widgets may overlap.",
    "bWidgetCollision=1",
    "",
]
for key, fades in ELEMENTS:
    ini += ["[%s]" % key, "fX=0", "fY=0", "fScale=1.00", "bHide=0"]
    if fades:
        ini.append("bAlwaysVisible=0")
    ini += ["sMoveWith=", ""]
ini += ["[Log]", "; 0 = trace ... 6 = off. Shipped at 2 (info).", "uLogLevel=2", ""]
ini_path = os.path.join(REPO, r"dist\OblivionRemastered\Binaries\Win64\OBSE\Plugins\HUDPositionManager.ini")
with open(ini_path, "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(ini))
print("INI ->", ini_path)
