# -*- coding: utf-8 -*-
"""The shipped files under dist/ (rule 66, rule 16): the eleven translation files for every TR key in src/Page.cpp,
and the INI with the compiled defaults.

    python tools/gen-dist.py

Keys the Skyrim HUD Position Manager already carries with the same meaning are taken from its eleven files
(6. current wip mods/HUDPositionManager/dist/Interface/Translations); the keys new to the remaster port, or whose
English changed, are in NEW below. The script fails loudly when a key used in the code has no text in a language."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SKYRIM = r"D:\Claude output\6. current wip mods\HUDPositionManager\dist\Interface\Translations"
OUT = os.path.join(REPO, r"dist\OblivionRemastered\Binaries\Win64\OBSE\Plugins\ApocryphaMenuFramework\Translations")
LANGS = ["english", "japanese", "korean", "chinese", "russian", "german", "french", "spanish", "italian", "polish", "czech"]

REUSE = {"HPM_Intro", "HPM_Enabled", "HPM_NoHud", "HPM_MoveX", "HPM_MoveY", "HPM_Size", "HPM_Hide", "HPM_ResetOne", "HPM_ResetAll",
         "HPM_El_Health", "HPM_El_Magicka", "HPM_El_Compass", "HPM_El_Crosshair", "HPM_El_EnemyHealth", "HPM_MoveWith",
         "HPM_MoveWithNone", "HPM_LinkBars"}

# key -> [english, japanese, korean, chinese, russian, german, french, spanish, italian, polish, czech]
NEW = {
    "HPM_EnabledHint": [
        "Off: every element goes back to where the game puts it.",
        "オフ: すべての要素がゲーム本来の位置に戻ります。",
        "끄면 모든 요소가 게임이 정한 위치로 돌아갑니다.",
        "关闭：每个元素都回到游戏默认的位置。",
        "Выкл.: каждый элемент возвращается туда, где его размещает игра.",
        "Aus: jedes Element kehrt dorthin zurück, wo das Spiel es platziert.",
        "Désactivé : chaque élément revient là où le jeu le place.",
        "Desactivado: cada elemento vuelve a donde lo coloca el juego.",
        "Disattivato: ogni elemento torna dove lo colloca il gioco.",
        "Wyłączone: każdy element wraca tam, gdzie umieszcza go gra.",
        "Vypnuto: každý prvek se vrátí tam, kam ho umisťuje hra.",
    ],
    "HPM_NotFound": [
        "Not in your HUD right now: it may appear later, or the HUD you use may not have it. Its settings are kept.",
        "現在HUDにありません。後で表示されるか、使用中のHUDには存在しない可能性があります。設定は保持されます。",
        "지금 HUD에 없습니다. 나중에 나타나거나, 사용 중인 HUD에 없을 수 있습니다. 설정은 유지됩니다.",
        "当前不在你的HUD中：它可能稍后出现，或你使用的HUD没有它。其设置会保留。",
        "Сейчас его нет в вашем HUD: он может появиться позже, или в вашем HUD его нет. Настройки сохраняются.",
        "Derzeit nicht in deinem HUD: es kann später erscheinen, oder dein HUD hat es nicht. Die Einstellungen bleiben erhalten.",
        "Absent de votre ATH pour l'instant : il peut apparaître plus tard, ou votre ATH ne l'a pas. Ses réglages sont conservés.",
        "Ahora no está en tu HUD: puede aparecer más tarde, o el HUD que usas no lo tiene. Sus ajustes se conservan.",
        "Ora non è nel tuo HUD: potrebbe comparire più tardi, o l'HUD che usi non lo ha. Le sue impostazioni sono conservate.",
        "Teraz nie ma go w twoim HUD: może pojawić się później albo używany HUD go nie ma. Ustawienia są zachowane.",
        "Teď není ve vašem HUD: může se objevit později, nebo ho váš HUD nemá. Nastavení zůstává zachováno.",
    ],
    "HPM_Found": [
        "In your HUD. Changes show at once.",
        "HUDにあります。変更はすぐに反映されます。",
        "HUD에 있습니다. 변경 사항이 바로 표시됩니다.",
        "在你的HUD中。更改会立即显示。",
        "Есть в вашем HUD. Изменения видны сразу.",
        "In deinem HUD. Änderungen sind sofort sichtbar.",
        "Dans votre ATH. Les changements sont visibles aussitôt.",
        "En tu HUD. Los cambios se ven al instante.",
        "Nel tuo HUD. Le modifiche si vedono subito.",
        "W twoim HUD. Zmiany widać od razu.",
        "Ve vašem HUD. Změny se projeví hned.",
    ],
    "HPM_El_Fatigue": ["Fatigue", "疲労", "피로", "疲劳", "Усталость", "Ausdauer", "Fatigue", "Fatiga", "Fatica", "Zmęczenie", "Únava"],
    "HPM_El_WeaponIcon": ["Weapon icon", "武器アイコン", "무기 아이콘", "武器图标", "Значок оружия", "Waffensymbol", "Icône d'arme", "Icono de arma", "Icona dell'arma", "Ikona broni", "Ikona zbraně"],
    "HPM_El_MagicIcon": ["Spell icon", "呪文アイコン", "주문 아이콘", "法术图标", "Значок заклинания", "Zaubersymbol", "Icône de sort", "Icono de hechizo", "Icona dell'incantesimo", "Ikona zaklęcia", "Ikona kouzla"],
    "HPM_El_EffectIcons": ["Active effects", "有効な効果", "활성 효과", "生效效果", "Активные эффекты", "Aktive Effekte", "Effets actifs", "Efectos activos", "Effetti attivi", "Aktywne efekty", "Aktivní efekty"],
    "HPM_El_SneakEye": ["Sneak eye", "隠密の目", "은신 눈", "潜行之眼", "Глаз скрытности", "Schleichauge", "Œil de furtivité", "Ojo de sigilo", "Occhio furtivo", "Oko skradania", "Oko plížení"],
    "HPM_El_LevelUp": ["Level-up gauge", "レベルアップゲージ", "레벨 업 게이지", "升级计量条", "Индикатор уровня", "Aufstiegsanzeige", "Jauge de niveau", "Indicador de nivel", "Indicatore di livello", "Wskaźnik awansu", "Ukazatel postupu"],
    "HPM_El_Info": ["Target name and value", "対象の名前と価値", "대상 이름과 가치", "目标名称与价值", "Имя и цена цели", "Name und Wert des Ziels", "Nom et valeur de la cible", "Nombre y valor del objetivo", "Nome e valore del bersaglio", "Nazwa i wartość celu", "Název a hodnota cíle"],
    "HPM_El_Subtitles": ["Subtitles and notifications", "字幕と通知", "자막과 알림", "字幕与通知", "Субтитры и уведомления", "Untertitel und Meldungen", "Sous-titres et notifications", "Subtítulos y notificaciones", "Sottotitoli e notifiche", "Napisy i powiadomienia", "Titulky a oznámení"],
    "HPM_El_Breath": ["Breath meter", "息メーター", "숨 게이지", "屏息计量条", "Индикатор дыхания", "Atemanzeige", "Jauge de souffle", "Indicador de aire", "Indicatore del respiro", "Wskaźnik oddechu", "Ukazatel dechu"],
    "HPM_El_Location": ["Location name", "場所の名前", "지역 이름", "地点名称", "Название места", "Ortsname", "Nom du lieu", "Nombre del lugar", "Nome del luogo", "Nazwa miejsca", "Název místa"],
    "HPM_El_DamageIndicators": ["Warning icons", "警告アイコン", "경고 아이콘", "警告图标", "Значки предупреждений", "Warnsymbole", "Icônes d'alerte", "Iconos de aviso", "Icone di avviso", "Ikony ostrzeżeń", "Varovné ikony"],
    "HPM_El_Notifications": ["Pop-up notifications", "ポップアップ通知", "팝업 알림", "弹出通知", "Всплывающие уведомления", "Einblendmeldungen", "Notifications contextuelles", "Notificaciones emergentes", "Notifiche a comparsa", "Powiadomienia wyskakujące", "Vyskakovací oznámení"],
    "HPM_El_Tutorial": ["Tutorial messages", "チュートリアルメッセージ", "튜토리얼 메시지", "教程提示", "Сообщения обучения", "Tutorial-Meldungen", "Messages du tutoriel", "Mensajes del tutorial", "Messaggi del tutorial", "Komunikaty samouczka", "Zprávy výuky"],
    "HPM_AlwaysOne": ["Always visible", "常に表示", "항상 표시", "始终显示", "Всегда видно", "Immer sichtbar", "Toujours visible", "Siempre visible", "Sempre visibile", "Zawsze widoczne", "Vždy viditelné"],
    "HPM_AlwaysOneHint": [
        "The game fades this out on its own. On: it stays shown while you play.",
        "ゲームはこれを自動で薄くします。オン: プレイ中は表示されたままになります。",
        "게임이 이것을 스스로 흐리게 합니다. 켜면 플레이 중에 계속 표시됩니다.",
        "游戏会自行将其淡出。开启：游戏中保持显示。",
        "Игра сама плавно скрывает это. Вкл.: остаётся видимым во время игры.",
        "Das Spiel blendet es von selbst aus. An: es bleibt beim Spielen sichtbar.",
        "Le jeu l'estompe de lui-même. Activé : il reste affiché pendant le jeu.",
        "El juego lo atenúa por sí solo. Activado: permanece visible mientras juegas.",
        "Il gioco lo dissolve da solo. Attivato: resta visibile mentre giochi.",
        "Gra sama go wygasza. Włączone: pozostaje widoczny podczas gry.",
        "Hra ho sama nechá zmizet. Zapnuto: zůstane zobrazený během hry.",
    ],
    "HPM_LinkedHint": [
        "Moves with Health while \"Move the three bars together\" is on.",
        "「3つのバーを一緒に動かす」がオンの間は体力と一緒に動きます。",
        "\"세 막대를 함께 이동\"이 켜져 있는 동안 체력과 함께 움직입니다.",
        "开启“三条栏一起移动”时随生命值一起移动。",
        "Движется вместе со здоровьем, пока включено «Двигать три полосы вместе».",
        "Bewegt sich mit der Gesundheit, solange „Die drei Leisten zusammen bewegen“ an ist.",
        "Se déplace avec la santé tant que « Déplacer les trois barres ensemble » est activé.",
        "Se mueve con la salud mientras \"Mover las tres barras juntas\" está activado.",
        "Si muove con la salute finché \"Sposta le tre barre insieme\" è attivo.",
        "Porusza się razem ze zdrowiem, gdy włączone jest „Przesuwaj trzy paski razem”.",
        "Pohybuje se se zdravím, dokud je zapnuto „Posouvat tři lišty společně“.",
    ],
    "HPM_LinkBarsHint": [
        "Magicka and Fatigue move with Health.",
        "マジカと疲労は体力と一緒に動きます。",
        "매지카와 피로가 체력과 함께 움직입니다.",
        "魔力与疲劳随生命值一起移动。",
        "Магия и усталость движутся вместе со здоровьем.",
        "Magicka und Ausdauer bewegen sich mit der Gesundheit.",
        "La magie et la fatigue se déplacent avec la santé.",
        "La magia y la fatiga se mueven con la salud.",
        "Magicka e fatica si muovono con la salute.",
        "Magia i zmęczenie poruszają się razem ze zdrowiem.",
        "Magie a únava se pohybují se zdravím.",
    ],
    "HPM_GroupVisibility": ["HUD visibility", "HUDの表示", "HUD 표시", "HUD显示", "Видимость HUD", "HUD-Sichtbarkeit", "Visibilité de l'ATH", "Visibilidad del HUD", "Visibilità dell'HUD", "Widoczność HUD", "Viditelnost HUD"],
    "HPM_AlwaysAll": ["Always visible", "常に表示", "항상 표시", "始终显示", "Всегда видно", "Immer sichtbar", "Toujours visible", "Siempre visible", "Sempre visibile", "Zawsze widoczne", "Vždy viditelné"],
    "HPM_AlwaysAllOnHint": [
        "The bars stay shown while you play. Menus, dialogue and loading screens still hide the HUD.",
        "プレイ中はバーが表示されたままになります。メニュー、会話、ロード画面ではHUDは引き続き隠れます。",
        "플레이 중에는 막대가 계속 표시됩니다. 메뉴, 대화, 로딩 화면에서는 HUD가 여전히 숨겨집니다.",
        "游戏中各栏保持显示。菜单、对话和加载画面仍会隐藏HUD。",
        "Полосы остаются видимыми во время игры. В меню, диалогах и на экранах загрузки HUD по-прежнему скрыт.",
        "Die Leisten bleiben beim Spielen sichtbar. Menüs, Gespräche und Ladebildschirme blenden das HUD weiterhin aus.",
        "Les barres restent affichées pendant le jeu. Les menus, les dialogues et les écrans de chargement masquent toujours l'ATH.",
        "Las barras permanecen visibles mientras juegas. Los menús, los diálogos y las pantallas de carga siguen ocultando el HUD.",
        "Le barre restano visibili mentre giochi. Menu, dialoghi e schermate di caricamento nascondono comunque l'HUD.",
        "Paski pozostają widoczne podczas gry. Menu, dialogi i ekrany ładowania nadal ukrywają HUD.",
        "Lišty zůstávají zobrazené během hry. Nabídky, dialogy a načítací obrazovky HUD nadále skrývají.",
    ],
    "HPM_AlwaysAllOffHint": [
        "Off: the game decides. The bars fade out when they are full.",
        "オフ: ゲームが決めます。バーは満タンになると薄くなります。",
        "끄면 게임이 결정합니다. 막대는 가득 차면 흐려집니다.",
        "关闭：由游戏决定。各栏满时会淡出。",
        "Выкл.: решает игра. Полосы плавно исчезают, когда заполнены.",
        "Aus: das Spiel entscheidet. Die Leisten blenden aus, wenn sie voll sind.",
        "Désactivé : le jeu décide. Les barres s'estompent quand elles sont pleines.",
        "Desactivado: decide el juego. Las barras se atenúan cuando están llenas.",
        "Disattivato: decide il gioco. Le barre si dissolvono quando sono piene.",
        "Wyłączone: decyduje gra. Paski gasną, gdy są pełne.",
        "Vypnuto: rozhoduje hra. Lišty zmizí, když jsou plné.",
    ],
    # the Presets tab (2026-09-29)
    "HPM_TabPresets": [
        "Presets",
        "プリセット",
        "프리셋",
        "预设",
        "Пресеты",
        "Voreinstellungen",
        "Préréglages",
        "Ajustes predefinidos",
        "Preimpostazioni",
        "Ustawienia wstępne",
        "Předvolby",
    ],
    "HPM_TabLayout": [
        "Layout",
        "レイアウト",
        "레이아웃",
        "布局",
        "Расположение",
        "Layout",
        "Disposition",
        "Diseño",
        "Disposizione",
        "Układ",
        "Rozložení",
    ],
    "HPM_PresetsIntro": [
        "A preset is a whole layout: every element's position, size and visibility. Load one made by someone else, or save your own to switch between.",
        "プリセットはレイアウト全体です: 各要素の位置、大きさ、表示。他の人が作ったものを読み込むか、自分のものを保存して切り替えられます。",
        "프리셋은 레이아웃 전체입니다: 각 요소의 위치, 크기, 표시 여부. 다른 사람이 만든 것을 불러오거나, 자신의 것을 저장해 전환할 수 있습니다.",
        "预设是完整的布局：每个元素的位置、大小和显示。载入他人制作的预设，或保存自己的预设以便切换。",
        "Пресет — это вся компоновка: положение, размер и видимость каждого элемента. Загрузите чужой или сохраните свои, чтобы переключаться между ними.",
        "Eine Voreinstellung ist ein ganzes Layout: Position, Größe und Sichtbarkeit jedes Elements. Lade eine von jemand anderem oder speichere deine eigenen, um zwischen ihnen zu wechseln.",
        "Un préréglage est une disposition complète : position, taille et visibilité de chaque élément. Chargez-en un fait par quelqu'un d'autre, ou enregistrez les vôtres pour passer de l'un à l'autre.",
        "Un ajuste predefinido es un diseño completo: posición, tamaño y visibilidad de cada elemento. Carga uno hecho por otra persona o guarda los tuyos para cambiar entre ellos.",
        "Una preimpostazione è una disposizione completa: posizione, dimensione e visibilità di ogni elemento. Caricane una fatta da altri, o salva le tue per passare dall'una all'altra.",
        "Ustawienie wstępne to cały układ: pozycja, rozmiar i widoczność każdego elementu. Wczytaj czyjeś albo zapisz własne, aby się między nimi przełączać.",
        "Předvolba je celé rozložení: poloha, velikost a viditelnost každého prvku. Načtěte cizí, nebo si uložte vlastní a přepínejte mezi nimi.",
    ],
    "HPM_PresetsNone": [
        "No presets yet. Save your layout below, or put a preset file from another author in the folder above.",
        "プリセットはまだありません。下でレイアウトを保存するか、他の作者のプリセットファイルを上のフォルダーに入れてください。",
        "아직 프리셋이 없습니다. 아래에서 레이아웃을 저장하거나, 다른 제작자의 프리셋 파일을 위 폴더에 넣으세요.",
        "还没有预设。在下方保存你的布局，或将其他作者的预设文件放入上面的文件夹。",
        "Пресетов пока нет. Сохраните свою компоновку ниже или положите файл пресета другого автора в папку выше.",
        "Noch keine Voreinstellungen. Speichere unten dein Layout oder lege die Voreinstellungsdatei eines anderen Autors in den Ordner oben.",
        "Aucun préréglage pour l'instant. Enregistrez votre disposition ci-dessous, ou placez le fichier de préréglage d'un autre auteur dans le dossier ci-dessus.",
        "Aún no hay ajustes predefinidos. Guarda tu diseño abajo o coloca el archivo de otro autor en la carpeta de arriba.",
        "Nessuna preimpostazione ancora. Salva la tua disposizione qui sotto, o metti il file di un altro autore nella cartella qui sopra.",
        "Brak ustawień wstępnych. Zapisz swój układ poniżej albo umieść plik innego autora w folderze powyżej.",
        "Zatím žádné předvolby. Uložte své rozložení níže, nebo vložte soubor předvolby jiného autora do složky výše.",
    ],
    "HPM_Preset": [
        "Preset",
        "プリセット",
        "프리셋",
        "预设",
        "Пресет",
        "Voreinstellung",
        "Préréglage",
        "Ajuste predefinido",
        "Preimpostazione",
        "Ustawienie wstępne",
        "Předvolba",
    ],
    "HPM_PresetLoad": [
        "Load this preset",
        "このプリセットを読み込む",
        "이 프리셋 불러오기",
        "载入此预设",
        "Загрузить этот пресет",
        "Diese Voreinstellung laden",
        "Charger ce préréglage",
        "Cargar este ajuste",
        "Carica questa preimpostazione",
        "Wczytaj to ustawienie",
        "Načíst tuto předvolbu",
    ],
    "HPM_PresetLoaded": [
        "Loaded",
        "読み込みました",
        "불러왔습니다",
        "已载入",
        "Загружено",
        "Geladen",
        "Chargé",
        "Cargado",
        "Caricata",
        "Wczytano",
        "Načteno",
    ],
    "HPM_PresetFailed": [
        "Could not read",
        "読み込めませんでした",
        "읽을 수 없습니다",
        "无法读取",
        "Не удалось прочитать",
        "Konnte nicht gelesen werden",
        "Lecture impossible",
        "No se pudo leer",
        "Impossibile leggere",
        "Nie można odczytać",
        "Nelze přečíst",
    ],
    "HPM_PresetDelete": [
        "Delete",
        "削除",
        "삭제",
        "删除",
        "Удалить",
        "Löschen",
        "Supprimer",
        "Eliminar",
        "Elimina",
        "Usuń",
        "Smazat",
    ],
    "HPM_PresetDeleteSure": [
        "Press again to delete",
        "もう一度押すと削除します",
        "다시 누르면 삭제됩니다",
        "再按一次以删除",
        "Нажмите ещё раз, чтобы удалить",
        "Zum Löschen erneut drücken",
        "Appuyez encore pour supprimer",
        "Pulsa de nuevo para eliminar",
        "Premi di nuovo per eliminare",
        "Naciśnij ponownie, aby usunąć",
        "Stiskněte znovu pro smazání",
    ],
    "HPM_PresetDeleted": [
        "Deleted",
        "削除しました",
        "삭제했습니다",
        "已删除",
        "Удалено",
        "Gelöscht",
        "Supprimé",
        "Eliminado",
        "Eliminata",
        "Usunięto",
        "Smazáno",
    ],
    "HPM_PresetDeleteFailed": [
        "Could not delete",
        "削除できませんでした",
        "삭제할 수 없습니다",
        "无法删除",
        "Не удалось удалить",
        "Konnte nicht gelöscht werden",
        "Suppression impossible",
        "No se pudo eliminar",
        "Impossibile eliminare",
        "Nie można usunąć",
        "Nelze smazat",
    ],
    "HPM_PresetSaveGroup": [
        "Save my layout",
        "自分のレイアウトを保存",
        "내 레이아웃 저장",
        "保存我的布局",
        "Сохранить мою компоновку",
        "Mein Layout speichern",
        "Enregistrer ma disposition",
        "Guardar mi diseño",
        "Salva la mia disposizione",
        "Zapisz mój układ",
        "Uložit mé rozložení",
    ],
    "HPM_PresetName": [
        "Name",
        "名前",
        "이름",
        "名称",
        "Название",
        "Name",
        "Nom",
        "Nombre",
        "Nome",
        "Nazwa",
        "Název",
    ],
    "HPM_PresetNameHint": [
        "With a controller, leave the name as it is: each save gets its own number.",
        "コントローラーの場合は名前をそのままにしてください: 保存するたびに番号が付きます。",
        "컨트롤러를 쓴다면 이름을 그대로 두세요: 저장할 때마다 번호가 붙습니다.",
        "使用手柄时保持名称不变：每次保存都会自动编号。",
        "С геймпадом оставьте название как есть: каждое сохранение получит свой номер.",
        "Mit einem Controller lass den Namen wie er ist: jede Speicherung bekommt ihre eigene Nummer.",
        "Avec une manette, laissez le nom tel quel : chaque enregistrement reçoit son propre numéro.",
        "Con mando, deja el nombre como está: cada guardado recibe su propio número.",
        "Con un controller lascia il nome com'è: ogni salvataggio riceve il proprio numero.",
        "Z padem zostaw nazwę bez zmian: każdy zapis dostaje własny numer.",
        "S ovladačem nechte název tak, jak je: každé uložení dostane vlastní číslo.",
    ],
    "HPM_PresetSave": [
        "Save as a preset",
        "プリセットとして保存",
        "프리셋으로 저장",
        "保存为预设",
        "Сохранить как пресет",
        "Als Voreinstellung speichern",
        "Enregistrer comme préréglage",
        "Guardar como ajuste predefinido",
        "Salva come preimpostazione",
        "Zapisz jako ustawienie wstępne",
        "Uložit jako předvolbu",
    ],
    "HPM_PresetSaveFailed": [
        "The preset could not be written.",
        "プリセットを書き込めませんでした。",
        "프리셋을 쓸 수 없습니다.",
        "无法写入预设。",
        "Не удалось записать пресет.",
        "Die Voreinstellung konnte nicht geschrieben werden.",
        "Le préréglage n'a pas pu être écrit.",
        "No se pudo escribir el ajuste predefinido.",
        "Impossibile scrivere la preimpostazione.",
        "Nie udało się zapisać ustawienia wstępnego.",
        "Předvolbu se nepodařilo zapsat.",
    ],
    "HPM_PresetSaved": [
        "Saved",
        "保存しました",
        "저장했습니다",
        "已保存",
        "Сохранено",
        "Gespeichert",
        "Enregistré",
        "Guardado",
        "Salvata",
        "Zapisano",
        "Uloženo",
    ],
    "HPM_PresetSaveTo": [
        "Save to",
        "保存先",
        "저장 위치",
        "保存到",
        "Сохранить в",
        "Speichern in",
        "Enregistrer dans",
        "Guardar en",
        "Salva in",
        "Zapisz do",
        "Uložit do",
    ],
    "HPM_PresetNew": [
        "New preset",
        "新しいプリセット",
        "새 프리셋",
        "新预设",
        "Новый пресет",
        "Neue Voreinstellung",
        "Nouveau préréglage",
        "Nuevo ajuste predefinido",
        "Nuova preimpostazione",
        "Nowe ustawienie wstępne",
        "Nová předvolba",
    ],
    "HPM_PresetUpdate": [
        "Update this preset with my layout",
        "このプリセットを今のレイアウトで更新",
        "이 프리셋을 내 레이아웃으로 업데이트",
        "用我的布局更新此预设",
        "Обновить этот пресет моей компоновкой",
        "Diese Voreinstellung mit meinem Layout aktualisieren",
        "Mettre à jour ce préréglage avec ma disposition",
        "Actualizar este ajuste con mi diseño",
        "Aggiorna questa preimpostazione con la mia disposizione",
        "Zaktualizuj to ustawienie moim układem",
        "Aktualizovat tuto předvolbu mým rozložením",
    ],
    "HPM_NoOverlap": [
        "HUD widget collision",
        "HUDウィジェットの衝突",
        "HUD 위젯 충돌",
        "HUD 组件碰撞",
        "Столкновение виджетов HUD",
        "HUD-Widget-Kollision",
        "Collision des widgets du HUD",
        "Colisión de widgets del HUD",
        "Collisione dei widget dell'HUD",
        "Kolizja widżetów HUD",
        "Kolize widgetů HUD",
    ],
    "HPM_NoOverlapHint": [
        "On: a widget you move stops where its edge meets another widget you have placed, so the bars line up without decimal-point work. Widgets the game still places are never in the way. Off: widgets may overlap.",
        "オン: 動かしたウィジェットは、自分で配置した別のウィジェットの端に当たったところで止まるので、小数点まで合わせなくてもバーが揃います。ゲームが配置したままのウィジェットは邪魔になりません。オフ: ウィジェットは重なることがあります。",
        "켜면 움직이는 위젯이 직접 배치한 다른 위젯의 가장자리에 닿는 곳에서 멈추므로 소수점까지 맞추지 않아도 막대가 정렬됩니다. 게임이 배치한 그대로인 위젯은 방해하지 않습니다. 끄면 위젯이 겹칠 수 있습니다.",
        "开启：移动的组件在其边缘碰到你放置过的另一组件时停止，这样各栏无需精确到小数点即可对齐。仍由游戏放置的组件不会挡路。关闭：组件可以重叠。",
        "Вкл.: перемещаемый виджет останавливается там, где его край касается другого виджета, который вы разместили, так что полосы выравниваются без подгонки до десятых. Виджеты, которые по-прежнему размещает игра, никогда не мешают. Выкл.: виджеты могут перекрываться.",
        "An: ein bewegtes Widget hält an, wo seine Kante auf ein Widget trifft, das du selbst platziert hast, so dass sich die Leisten ohne Kommastellen-Arbeit ausrichten. Widgets, die noch das Spiel platziert, stehen nie im Weg. Aus: Widgets dürfen sich überlappen.",
        "Activé : un widget déplacé s'arrête là où son bord rencontre un widget que vous avez placé, les barres s'alignent donc sans réglage à la décimale. Les widgets encore placés par le jeu ne gênent jamais. Désactivé : les widgets peuvent se chevaucher.",
        "Activado: un widget que muevas se detiene donde su borde toca otro widget que hayas colocado, así las barras se alinean sin ajustar decimales. Los widgets que aún coloca el juego nunca estorban. Desactivado: los widgets pueden superponerse.",
        "Attivato: un widget che sposti si ferma dove il suo bordo incontra un altro widget che hai posizionato, così le barre si allineano senza lavorare sui decimali. I widget ancora posizionati dal gioco non sono mai d'intralcio. Disattivato: i widget possono sovrapporsi.",
        "Włączone: przesuwany widżet zatrzymuje się tam, gdzie jego krawędź styka się z innym widżetem, który sam ustawiłeś, więc paski wyrównują się bez dłubania w ułamkach. Widżety wciąż ustawiane przez grę nigdy nie przeszkadzają. Wyłączone: widżety mogą się nakładać.",
        "Zapnuto: přesouvaný widget se zastaví tam, kde se jeho okraj dotkne jiného widgetu, který jste umístili, takže se lišty zarovnají bez ladění desetin. Widgety, které stále umisťuje hra, nikdy nepřekážejí. Vypnuto: widgety se mohou překrývat.",
    ],
    "HPM_El_QuickWheel": [
        "Quick wheel",
        "クイックホイール",
        "퀵 휠",
        "快捷轮盘",
        "Быстрое колесо",
        "Schnellrad",
        "Roue rapide",
        "Rueda rápida",
        "Ruota rapida",
        "Szybkie koło",
        "Rychlé kolo",
    ],
    "HPM_Snap": [
        "Snap art edges together",
        "アートの端を吸着させる",
        "아트 가장자리 맞춤",
        "贴齐图形边缘",
        "Прилипание краёв",
        "Kanten einrasten lassen",
        "Aimanter les bords",
        "Ajustar bordes entre sí",
        "Aggancia i bordi",
        "Przyciągaj krawędzie",
        "Přichytávat okraje",
    ],
    "HPM_SnapHint": [
        "On: when an edge of a widget you move comes close to an edge of another widget you have placed, it pulls onto that line, so two widgets meet or align exactly even when a slider tick overshoots. Off: widgets sit exactly where the sliders put them.",
        "オン: 動かしているウィジェットの端が、自分で配置した別のウィジェットの端に近づくとその線に吸着するので、スライダーの1目盛りが行き過ぎても2つのウィジェットがぴったり接したり揃ったりします。オフ: ウィジェットはスライダーの位置そのままです。",
        "켜면 움직이는 위젯의 가장자리가 직접 배치한 다른 위젯의 가장자리에 가까워질 때 그 선에 달라붙어, 슬라이더 한 칸이 지나치더라도 두 위젯이 정확히 맞닿거나 정렬됩니다. 끄면 위젯은 슬라이더가 둔 자리에 그대로 있습니다.",
        "开启：移动的组件边缘靠近你放置过的另一组件的边缘时会吸附到那条线上，即使滑块一格越过了位置，两个组件也能精确贴合或对齐。关闭：组件停在滑块设定的位置。",
        "Вкл.: когда край перемещаемого виджета подходит к краю другого виджета, который вы разместили, он прилипает к этой линии, так что два виджета точно смыкаются или выравниваются, даже если деление ползунка проскакивает. Выкл.: виджеты стоят ровно там, куда их ставят ползунки.",
        "An: kommt eine Kante eines bewegten Widgets nahe an eine Kante eines Widgets, das du platziert hast, rastet sie auf dieser Linie ein, so dass zwei Widgets genau aneinanderstoßen oder fluchten, auch wenn ein Schieberegler-Schritt darüber hinausschießt. Aus: Widgets sitzen genau dort, wo die Regler sie hinsetzen.",
        "Activé : quand un bord d'un widget déplacé s'approche d'un bord d'un autre widget que vous avez placé, il s'aimante sur cette ligne, et deux widgets se rejoignent ou s'alignent exactement même si un cran de curseur dépasse. Désactivé : les widgets restent exactement où les curseurs les mettent.",
        "Activado: cuando un borde del widget que mueves se acerca a un borde de otro widget que hayas colocado, se ajusta a esa línea, así dos widgets se juntan o alinean con exactitud aunque un paso del control deslizante se pase. Desactivado: los widgets quedan justo donde los ponen los controles.",
        "Attivato: quando un bordo del widget che sposti si avvicina a un bordo di un altro widget che hai posizionato, si aggancia a quella linea, così due widget si toccano o si allineano esattamente anche se uno scatto del cursore va oltre. Disattivato: i widget restano esattamente dove li mettono i cursori.",
        "Włączone: gdy krawędź przesuwanego widżetu zbliży się do krawędzi innego widżetu, który sam ustawiłeś, przyciąga się do tej linii, więc dwa widżety stykają się lub wyrównują dokładnie, nawet gdy jeden krok suwaka przeskoczy. Wyłączone: widżety stoją dokładnie tam, gdzie ustawią je suwaki.",
        "Zapnuto: když se okraj přesouvaného widgetu přiblíží k okraji jiného widgetu, který jste umístili, přichytí se na tu čáru, takže se dva widgety přesně dotknou nebo zarovnají, i když krok posuvníku přestřelí. Vypnuto: widgety stojí přesně tam, kam je posuvníky dají.",
    ],
    "HPM_SnapDistance": [
        "Snap distance",
        "吸着距離",
        "맞춤 거리",
        "贴齐距离",
        "Расстояние прилипания",
        "Einrastabstand",
        "Distance d'aimantation",
        "Distancia de ajuste",
        "Distanza di aggancio",
        "Odległość przyciągania",
        "Vzdálenost přichycení",
    ],
    "HPM_SnapDistanceHint": [
        "How close an edge has to come before it snaps, in screen units (the screen is 1080 tall).",
        "端が吸着するまでの距離。画面単位です (画面の高さは1080)。",
        "가장자리가 달라붙기 시작하는 거리. 화면 단위입니다 (화면 높이 1080).",
        "边缘开始吸附的距离，以屏幕单位计（屏幕高 1080）。",
        "Насколько близко должен подойти край, чтобы прилипнуть, в экранных единицах (высота экрана 1080).",
        "Wie nah eine Kante kommen muss, bevor sie einrastet, in Bildschirmeinheiten (der Bildschirm ist 1080 hoch).",
        "À quelle distance un bord doit arriver avant de s'aimanter, en unités d'écran (l'écran fait 1080 de haut).",
        "A qué distancia debe llegar un borde para ajustarse, en unidades de pantalla (la pantalla mide 1080 de alto).",
        "Quanto deve avvicinarsi un bordo prima di agganciarsi, in unità dello schermo (lo schermo è alto 1080).",
        "Jak blisko musi podejść krawędź, zanim się przyciągnie, w jednostkach ekranu (ekran ma 1080 wysokości).",
        "Jak blízko musí okraj přijít, než se přichytí, v jednotkách obrazovky (obrazovka je 1080 vysoká).",
    ],
    "HPM_Preview": [
        "Show every element",
        "すべての要素を表示",
        "모든 요소 표시",
        "显示所有元素",
        "Показывать все элементы",
        "Alle Elemente zeigen",
        "Afficher tous les éléments",
        "Mostrar todos los elementos",
        "Mostra ogni elemento",
        "Pokazuj wszystkie elementy",
        "Zobrazit všechny prvky",
    ],
    "HPM_PreviewHint": [
        "On: elements that only appear during an event (an enemy's health, the sneak eye, the level-up icon, subtitles) are made to show, in the menu and out of it, until you turn this off - so you can place them and look at the result. Turn it off when your layout is done. Off: the HUD shows only what the game shows.",
        "オン: イベント中にしか現れない要素 (敵の体力、スニークの目、レベルアップアイコン、字幕) を、メニューの内外を問わずオフにするまで表示させます。配置して結果を確認できます。レイアウトが済んだらオフにしてください。オフ: HUDはゲームが表示するものだけを表示します。",
        "켜면 이벤트 중에만 나타나는 요소(적의 체력, 은신 눈, 레벨 업 아이콘, 자막)가 메뉴 안팎에서 이 설정을 끌 때까지 표시되어 배치하고 결과를 볼 수 있습니다. 레이아웃이 끝나면 끄세요. 끄면 HUD는 게임이 보여주는 것만 보여줍니다.",
        "开启：只在事件期间出现的元素（敌人生命值、潜行之眼、升级图标、字幕）会在菜单内外持续显示，直到你关闭此项，便于放置并查看效果。布局完成后请关闭。关闭：HUD 只显示游戏本身显示的内容。",
        "Вкл.: элементы, появляющиеся только во время события (здоровье врага, глаз скрытности, значок повышения уровня, субтитры), показываются в меню и вне его, пока вы не выключите это, чтобы разместить их и увидеть результат. Выключите, когда компоновка готова. Выкл.: HUD показывает только то, что показывает игра.",
        "An: Elemente, die nur bei einem Ereignis erscheinen (die Gesundheit eines Gegners, das Schleichauge, das Stufenaufstiegssymbol, Untertitel), werden im Menü und außerhalb gezeigt, bis du dies ausschaltest, damit du sie platzieren und das Ergebnis ansehen kannst. Schalte es aus, wenn dein Layout fertig ist. Aus: das HUD zeigt nur, was das Spiel zeigt.",
        "Activé : les éléments qui n'apparaissent que pendant un événement (santé d'un ennemi, œil de furtivité, icône de montée de niveau, sous-titres) sont affichés, dans le menu et en dehors, jusqu'à ce que vous désactiviez ceci, pour les placer et voir le résultat. Désactivez-le une fois la disposition terminée. Désactivé : l'ATH ne montre que ce que le jeu montre.",
        "Activado: los elementos que solo aparecen durante un evento (la salud de un enemigo, el ojo de sigilo, el icono de subida de nivel, los subtítulos) se muestran, dentro y fuera del menú, hasta que lo desactives, para colocarlos y ver el resultado. Desactívalo cuando termines el diseño. Desactivado: el HUD muestra solo lo que muestra el juego.",
        "Attivato: gli elementi che compaiono solo durante un evento (la salute di un nemico, l'occhio furtivo, l'icona di salita di livello, i sottotitoli) sono mostrati, nel menu e fuori, finché non lo disattivi, così puoi posizionarli e vedere il risultato. Disattivalo quando la disposizione è pronta. Disattivato: l'HUD mostra solo ciò che mostra il gioco.",
        "Włączone: elementy pojawiające się tylko podczas zdarzenia (zdrowie wroga, oko skradania, ikona awansu, napisy) są pokazywane w menu i poza nim, dopóki tego nie wyłączysz, byś mógł je ustawić i obejrzeć efekt. Wyłącz, gdy układ jest gotowy. Wyłączone: HUD pokazuje tylko to, co pokazuje gra.",
        "Zapnuto: prvky, které se objevují jen během události (zdraví nepřítele, oko plížení, ikona postupu na další úroveň, titulky), se zobrazují v nabídce i mimo ni, dokud to nevypnete, abyste je mohli rozmístit a prohlédnout si výsledek. Až bude rozložení hotové, vypněte to. Vypnuto: HUD ukazuje jen to, co ukazuje hra.",
    ],
    "HPM_PreviewItem": [
        "Item name",
        "アイテム名",
        "아이템 이름",
        "物品名称",
        "Название предмета",
        "Gegenstandsname",
        "Nom de l'objet",
        "Nombre del objeto",
        "Nome dell'oggetto",
        "Nazwa przedmiotu",
        "Název předmětu",
    ],
    "HPM_PreviewSubtitle": [
        "A subtitle appears here while someone speaks.",
        "誰かが話している間、ここに字幕が表示されます。",
        "누군가 말하는 동안 여기에 자막이 표시됩니다.",
        "有人说话时字幕显示在这里。",
        "Пока кто-то говорит, здесь появляются субтитры.",
        "Hier erscheint ein Untertitel, während jemand spricht.",
        "Un sous-titre apparaît ici pendant qu'une personne parle.",
        "Aquí aparece un subtítulo mientras alguien habla.",
        "Qui compare un sottotitolo mentre qualcuno parla.",
        "Tutaj pojawiają się napisy, gdy ktoś mówi.",
        "Zde se zobrazují titulky, když někdo mluví.",
    ],
    "HPM_PreviewArea": [
        "Area name",
        "エリア名",
        "지역 이름",
        "区域名称",
        "Название области",
        "Gebietsname",
        "Nom du lieu",
        "Nombre de la zona",
        "Nome dell'area",
        "Nazwa obszaru",
        "Název oblasti",
    ],
    "HPM_El_Level": [
        "Level",
        "レベル",
        "레벨",
        "等级",
        "Уровень",
        "Stufe",
        "Niveau",
        "Nivel",
        "Livello",
        "Poziom",
        "Úroveň",
    ],
    "HPM_LevelText": [
        "Level {}",
        "レベル {}",
        "레벨 {}",
        "等级 {}",
        "Уровень {}",
        "Stufe {}",
        "Niveau {}",
        "Nivel {}",
        "Livello {}",
        "Poziom {}",
        "Úroveň {}",
    ],
    "HPM_Length": [
        "Length",
        "長さ",
        "길이",
        "长度",
        "Длина",
        "Länge",
        "Longueur",
        "Longitud",
        "Lunghezza",
        "Długość",
        "Délka",
    ],
    "HPM_Height": [
        "Height",
        "高さ",
        "높이",
        "高度",
        "Высота",
        "Höhe",
        "Hauteur",
        "Altura",
        "Altezza",
        "Wysokość",
        "Výška",
    ],
    "HPM_StretchHint": [
        "Length and Height stretch the bar on one side each, on top of Size.",
        "「長さ」と「高さ」は「大きさ」に加えて、バーを一方向ずつ伸縮させます。",
        "길이와 높이는 크기에 더해 막대를 한 방향씩 늘리거나 줄입니다.",
        "长度和高度在大小之外分别沿一个方向拉伸条形。",
        "Длина и высота растягивают полосу по одной оси каждая, поверх размера.",
        "Länge und Höhe strecken die Leiste je auf einer Seite, zusätzlich zur Größe.",
        "Longueur et Hauteur étirent la barre sur un côté chacune, en plus de la Taille.",
        "Longitud y Altura estiran la barra en un lado cada una, además del Tamaño.",
        "Lunghezza e Altezza allungano la barra su un lato ciascuna, oltre alla Dimensione.",
        "Długość i Wysokość rozciągają pasek każda po jednej stronie, oprócz Rozmiaru.",
        "Délka a Výška natahují lištu každá v jednom směru, nad rámec Velikosti.",
    ],
    "HPM_TabCombined": [
        "Combined widgets",
        "まとめて動かす",
        "함께 이동",
        "组合部件",
        "Совместное перемещение",
        "Gemeinsam bewegen",
        "Widgets combinés",
        "Widgets combinados",
        "Widget combinati",
        "Widżety połączone",
        "Spojené prvky",
    ],
    "HPM_CombinedIntro": [
        "Pick the widgets that should move as one. The sliders below move every picked widget together, on top of the position each has on its own tab.",
        "一緒に動かすウィジェットを選びます。下のスライダーは選んだすべてのウィジェットを、各タブで設定した位置に加えてまとめて動かします。",
        "함께 움직일 위젯을 고르세요. 아래 슬라이더는 고른 모든 위젯을 각 탭의 위치에 더해 한꺼번에 움직입니다.",
        "选择要一起移动的部件。下面的滑块会在每个部件各自标签页的位置之上，把所有选中的部件一起移动。",
        "Выберите виджеты, которые должны двигаться вместе. Ползунки ниже сдвигают все выбранные виджеты разом, поверх положения, заданного на вкладке каждого.",
        "Wähle die Widgets, die sich gemeinsam bewegen sollen. Die Regler unten bewegen alle gewählten Widgets zusammen, zusätzlich zur Position auf ihrem eigenen Reiter.",
        "Choisissez les widgets qui doivent bouger ensemble. Les curseurs ci-dessous déplacent tous les widgets choisis d'un bloc, en plus de la position réglée sur leur propre onglet.",
        "Elige los widgets que deben moverse como uno. Los controles de abajo mueven todos los widgets elegidos a la vez, además de la posición de su propia pestaña.",
        "Scegli i widget che devono muoversi insieme. I cursori qui sotto spostano tutti i widget scelti in blocco, oltre alla posizione della loro scheda.",
        "Wybierz widżety, które mają poruszać się razem. Suwaki poniżej przesuwają wszystkie wybrane widżety naraz, niezależnie od pozycji ustawionej na ich własnych kartach.",
        "Vyberte prvky, které se mají pohybovat společně. Posuvníky níže posouvají všechny vybrané prvky naráz, nad rámec polohy nastavené na jejich vlastní kartě.",
    ],
    "HPM_GroupMembers": [
        "Widgets that move as one",
        "一緒に動くウィジェット",
        "함께 움직이는 위젯",
        "一起移动的部件",
        "Виджеты, движущиеся вместе",
        "Gemeinsam bewegte Widgets",
        "Widgets qui bougent ensemble",
        "Widgets que se mueven juntos",
        "Widget che si muovono insieme",
        "Widżety poruszające się razem",
        "Prvky pohybující se společně",
    ],
    "HPM_GroupNone": [
        "Pick two or more widgets above to move them together.",
        "上で2つ以上のウィジェットを選ぶと、まとめて動かせます。",
        "위에서 위젯을 둘 이상 고르면 함께 움직일 수 있습니다.",
        "在上方选择两个或更多部件即可一起移动。",
        "Выберите выше два виджета или больше, чтобы двигать их вместе.",
        "Wähle oben zwei oder mehr Widgets, um sie gemeinsam zu bewegen.",
        "Choisissez deux widgets ou plus ci-dessus pour les déplacer ensemble.",
        "Elige dos o más widgets arriba para moverlos juntos.",
        "Scegli due o più widget qui sopra per spostarli insieme.",
        "Wybierz powyżej dwa lub więcej widżetów, aby przesuwać je razem.",
        "Vyberte výše dva nebo více prvků, aby se pohybovaly společně.",
    ],
    "HPM_GroupReset": [
        "Reset the shared position",
        "共通の位置をリセット",
        "공통 위치 초기화",
        "重置共享位置",
        "Сбросить общее положение",
        "Gemeinsame Position zurücksetzen",
        "Réinitialiser la position commune",
        "Restablecer la posición compartida",
        "Azzera la posizione condivisa",
        "Resetuj wspólną pozycję",
        "Obnovit společnou polohu",
    ],
    "HPM_InGroupHint": [
        "Also moves with the widgets on the Combined widgets tab.",
        "「まとめて動かす」タブのウィジェットとも一緒に動きます。",
        "함께 이동 탭의 위젯과도 같이 움직입니다.",
        "也会随组合部件标签页中的部件一起移动。",
        "Также движется вместе с виджетами на вкладке совместного перемещения.",
        "Bewegt sich auch mit den Widgets auf dem Reiter „Gemeinsam bewegen“.",
        "Bouge aussi avec les widgets de l'onglet Widgets combinés.",
        "También se mueve con los widgets de la pestaña Widgets combinados.",
        "Si muove anche con i widget della scheda Widget combinati.",
        "Porusza się też razem z widżetami z karty Widżety połączone.",
        "Pohybuje se také s prvky na kartě Spojené prvky.",
    ],
    "HPM_BarsSection": [
        "Resource bars",
        "リソースバー",
        "자원 막대",
        "资源条",
        "Полосы ресурсов",
        "Ressourcenleisten",
        "Barres de ressources",
        "Barras de recursos",
        "Barre delle risorse",
        "Paski zasobów",
        "Lišty zdrojů",
    ],
    "HPM_FillFrom": [
        "Fill from",
        "塗りの起点",
        "채움 방향",
        "填充起点",
        "Заполнение от",
        "Füllung von",
        "Remplissage depuis",
        "Relleno desde",
        "Riempimento da",
        "Wypełnienie od",
        "Plnění od",
    ],
    "HPM_FillGame": [
        "The game's own",
        "ゲーム本来",
        "게임 기본",
        "游戏默认",
        "Как в игре",
        "Wie im Spiel",
        "Celui du jeu",
        "El del juego",
        "Quello del gioco",
        "Jak w grze",
        "Jako ve hře",
    ],
    "HPM_FillLeft": [
        "Left",
        "左",
        "왼쪽",
        "左",
        "Слева",
        "Links",
        "Gauche",
        "Izquierda",
        "Sinistra",
        "Lewo",
        "Zleva",
    ],
    "HPM_FillCentre": [
        "Centre",
        "中央",
        "가운데",
        "中间",
        "Центр",
        "Mitte",
        "Centre",
        "Centro",
        "Centro",
        "Środek",
        "Střed",
    ],
    "HPM_FillRight": [
        "Right",
        "右",
        "오른쪽",
        "右",
        "Справа",
        "Rechts",
        "Droite",
        "Derecha",
        "Destra",
        "Prawo",
        "Zprava",
    ],
    "HPM_FillHint": [
        "Fill from: the side the filled part of a bar is anchored to - it drains away from that side. Centre drains toward both ends.",
        "塗りの起点: バーの塗りが固定される側です。減るときはその側から離れていきます。「中央」は両端に向かって減ります。",
        "채움 방향: 막대의 채워진 부분이 고정되는 쪽입니다. 줄어들 때 그쪽에서 멀어집니다. 가운데는 양 끝으로 줄어듭니다.",
        "填充起点：条的已填充部分固定在哪一侧，减少时从该侧向外收缩。中间则向两端收缩。",
        "Заполнение от: сторона, к которой прижата заполненная часть полосы - убывая, она отходит от неё. Центр убывает к обоим концам.",
        "Füllung von: die Seite, an der der gefüllte Teil der Leiste hängt - er schwindet von dieser Seite weg. Mitte schwindet zu beiden Enden.",
        "Remplissage depuis : le côté auquel la partie remplie de la barre est ancrée - elle se vide en s'en éloignant. Centre se vide vers les deux bouts.",
        "Relleno desde: el lado al que se ancla la parte llena de la barra; al vaciarse se aleja de ese lado. Centro se vacía hacia ambos extremos.",
        "Riempimento da: il lato a cui è ancorata la parte piena della barra - svuotandosi se ne allontana. Centro si svuota verso entrambe le estremità.",
        "Wypełnienie od: strona, do której przylega wypełniona część paska - ubywa jej od tej strony. Środek ubywa ku obu końcom.",
        "Plnění od: strana, ke které je naplněná část lišty ukotvena - ubývá směrem od ní. Střed ubývá k oběma koncům.",
    ],
    "HPM_LinkLength": [
        "Length follows the resource",
        "長さを最大値に連動",
        "길이를 최대치에 연동",
        "长度随资源上限",
        "Длина следует за ресурсом",
        "Länge folgt dem Maximum",
        "Longueur liée à la ressource",
        "Longitud según el recurso",
        "Lunghezza legata alla risorsa",
        "Długość zależna od zasobu",
        "Délka podle zdroje",
    ],
    "HPM_LinkLengthHint": [
        "The bar grows with your maximum: it is 1.00x long at the points below, longer above them.",
        "バーは最大値に応じて伸びます。下のポイント数で1.00倍、それを超えると長くなります。",
        "막대가 최대치에 따라 길어집니다. 아래 포인트에서 1.00배, 그 이상이면 더 길어집니다.",
        "条会随上限增长：达到下方点数时为1.00倍，超过则更长。",
        "Полоса растёт вместе с максимумом: при указанных ниже очках она длиной 1,00x, выше - длиннее.",
        "Die Leiste wächst mit deinem Maximum: bei den Punkten unten ist sie 1,00x lang, darüber länger.",
        "La barre grandit avec votre maximum : elle fait 1,00x aux points ci-dessous, plus au-delà.",
        "La barra crece con tu máximo: mide 1,00x en los puntos de abajo, más por encima.",
        "La barra cresce con il tuo massimo: è lunga 1,00x ai punti qui sotto, di più oltre.",
        "Pasek rośnie wraz z maksimum: przy punktach poniżej ma długość 1,00x, powyżej jest dłuższy.",
        "Lišta roste s vaším maximem: při bodech níže má délku 1,00x, nad nimi je delší.",
    ],
    "HPM_PointsPerLength": [
        "Points per full length",
        "1.00倍になるポイント数",
        "1.00배 기준 포인트",
        "1.00倍对应点数",
        "Очков на полную длину",
        "Punkte für volle Länge",
        "Points pour la longueur 1,00x",
        "Puntos para la longitud 1,00x",
        "Punti per la lunghezza 1,00x",
        "Punkty na pełną długość",
        "Body na plnou délku",
    ],
    "HPM_GrowSide": [
        "Grows toward",
        "伸びる方向",
        "늘어나는 방향",
        "增长方向",
        "Растёт в сторону",
        "Wächst nach",
        "S'allonge vers",
        "Crece hacia",
        "Cresce verso",
        "Rośnie w stronę",
        "Roste směrem",
    ],
    "HPM_GrowBoth": [
        "Both sides",
        "両側",
        "양쪽",
        "两侧",
        "В обе стороны",
        "Beide Seiten",
        "Les deux côtés",
        "Ambos lados",
        "Entrambi i lati",
        "Obie strony",
        "Obě strany",
    ],
    "HPM_GrowRight": [
        "The right",
        "右",
        "오른쪽",
        "右侧",
        "Вправо",
        "Rechts",
        "La droite",
        "La derecha",
        "La destra",
        "W prawo",
        "Doprava",
    ],
    "HPM_GrowLeft": [
        "The left",
        "左",
        "왼쪽",
        "左侧",
        "Влево",
        "Links",
        "La gauche",
        "La izquierda",
        "La sinistra",
        "W lewo",
        "Doleva",
    ],
    "HPM_GrowHint": [
        "Which way the bar gets longer or shorter: from its centre, or anchored on one end so it grows toward the other.",
        "バーが伸縮する方向です。中央から、または片端を固定してもう一方へ伸びます。",
        "막대가 길어지거나 짧아지는 방향입니다. 가운데에서, 또는 한쪽 끝을 고정하고 반대쪽으로 늘어납니다.",
        "条变长或变短的方向：从中间，或固定一端向另一端增长。",
        "Куда полоса удлиняется или укорачивается: от центра, или закреплённая одним концом - к другому.",
        "In welche Richtung die Leiste länger oder kürzer wird: von der Mitte aus, oder an einem Ende verankert zum anderen hin.",
        "Dans quel sens la barre s'allonge ou se raccourcit : depuis son centre, ou ancrée à un bout vers l'autre.",
        "Hacia dónde se alarga o acorta la barra: desde su centro, o anclada en un extremo hacia el otro.",
        "In che direzione la barra si allunga o si accorcia: dal centro, o ancorata a un'estremità verso l'altra.",
        "W którą stronę pasek się wydłuża lub skraca: od środka, albo zakotwiczony na jednym końcu w stronę drugiego.",
        "Kterým směrem se lišta prodlužuje nebo zkracuje: od středu, nebo ukotvená na jednom konci směrem k druhému.",
    ],
    "HPM_PlacedByMinimap": [
        "Placed by Minimap Menu right now: the sliders below wait until the minimap lets go of it.",
        "現在はMinimap Menuが配置しています。ミニマップが手放すまで、下のスライダーは待機します。",
        "지금은 Minimap Menu가 배치합니다. 미니맵이 놓아줄 때까지 아래 슬라이더는 대기합니다.",
        "当前由 Minimap Menu 放置：下面的滑块要等小地图放开它后才生效。",
        "Сейчас его размещает Minimap Menu: ползунки ниже ждут, пока миникарта его отпустит.",
        "Wird gerade von Minimap Menu platziert: die Regler unten warten, bis die Minikarte es freigibt.",
        "Placé par Minimap Menu pour l'instant : les curseurs ci-dessous attendent que la minicarte le libère.",
        "Colocado ahora por Minimap Menu: los controles de abajo esperan a que el minimapa lo suelte.",
        "Ora lo colloca Minimap Menu: i cursori qui sotto aspettano che la minimappa lo lasci.",
        "Teraz umieszcza go Minimap Menu: suwaki poniżej czekają, aż minimapa go puści.",
        "Teď ho umisťuje Minimap Menu: posuvníky níže čekají, až ho minimapa pustí.",
    ],
}


def read_translation(path):
    raw = open(path, "rb").read()
    text = raw[2:].decode("utf-16-le") if raw[:2] == b"\xff\xfe" else raw.decode("utf-8-sig")
    out = {}
    for line in text.splitlines():
        if line.startswith("$") and "\t" in line:
            k, v = line[1:].split("\t", 1)
            out[k] = v
    return out


code = open(os.path.join(REPO, "src", "Page.cpp"), encoding="utf-8").read()
used = sorted(set(re.findall(r'\bTR\s*\(\s*"([A-Za-z0-9_]+)"', code)))
english_in_code = dict(re.findall(r'\bTR\s*\(\s*"([A-Za-z0-9_]+)"\s*,\s*"((?:[^"\\]|\\.)*)"', code))
# the preview placeholders live in Elements.h as ArgText("<param>", "<key>", "<english>")
elements_src = open(os.path.join(REPO, "src", "Elements.h"), encoding="utf-8").read()
for k, en in re.findall(r'ArgText\("[^"]*",\s*"(HPM_[A-Za-z0-9_]+)",\s*"((?:[^"\\]|\\.)*)"\)', elements_src):
    used.append(k)
    english_in_code[k] = en
hud_src = open(os.path.join(REPO, "src", "Hud.cpp"), encoding="utf-8").read()
for k, en in re.findall(r'strings::Get\("(HPM_[A-Za-z0-9_]+)",\s*"((?:[^"\\]|\\.)*)"\)', hud_src):
    used.append(k)
    english_in_code[k] = en
used = sorted(set(used))
os.makedirs(OUT, exist_ok=True)
for li, lang in enumerate(LANGS):
    sky = read_translation(os.path.join(SKYRIM, "HUDPositionManager_%s.txt" % lang))
    lines = []
    for key in used:
        if key in NEW:
            text = NEW[key][li]
        elif key in REUSE and key in sky:
            text = sky[key] if lang != "english" else english_in_code.get(key, sky[key]).replace('\\"', '"')
        else:
            raise SystemExit("no %s text for %s" % (lang, key))
        lines.append("$%s\t%s" % (key, text))
    with open(os.path.join(OUT, "HUDPositionManager_%s.txt" % lang), "wb") as f:
        f.write(b"\xff\xfe" + ("\r\n".join(lines) + "\r\n").encode("utf-16-le"))
print("%d keys x %d languages -> %s" % (len(used), len(LANGS), OUT))

# the INI with the compiled defaults (Settings.h / Elements.h)
# (key, fades, bar, stat) in Elements.h order
ELEMENTS = [
    ("Health", True, True, True), ("Magicka", True, True, True), ("Fatigue", True, True, True), ("Breath", True, True, False), ("Compass", True, False, False),
    ("QuickWheel", False, False, False), ("Crosshair", False, False, False), ("WeaponIcon", False, False, False), ("MagicIcon", False, False, False),
    ("EffectIcons", False, False, False), ("EnemyHealth", False, True, False), ("SneakEye", False, False, False), ("LevelUp", False, False, False),
    ("Level", False, False, False), ("Info", False, False, False), ("Subtitles", False, False, False), ("Location", False, False, False),
    ("DamageIndicators", True, False, False), ("Notifications", False, False, False), ("Tutorial", False, False, False),
]
ini = [
    "; HUD Position Manager for Oblivion - settings. The settings page in Apocrypha Menu Framework writes this file;",
    "; edit it by hand only with the game closed. fX / fY are a percentage of the screen's width / height (the same layout",
    "; on every resolution); fScale 1.00 = the game's size.",
    "",
    "[General]",
    "; Apply my layout: 0 puts every element back where the game places it.",
    "bEnabled=1",
    "; HUD visibility: 0 = the game decides (the bars fade out when full), 1 = the bars stay shown while you play.",
    "bAlwaysVisible=0",
    "; Snap art edges together: 1 = an edge of a widget you move pulls onto a nearby edge of another widget you have placed; 0 = widgets sit where the sliders put them.",
    "bSnapEdges=0",
    "; Snap distance: how close an edge has to come before it snaps, in screen units (the screen is 1080 tall).",
    "fSnapDistance=6",
    "; Show every element: 1 = event-only elements are made to show, in the menu and out of it, until turned off (for laying them out); 0 = the HUD shows only what the game shows.",
    "bPreview=0",
    "; HUD widget collision: 1 = a widget you move stops where its edge meets another widget you have placed (a game-placed one is never in the way); 0 = widgets may overlap.",
    "bWidgetCollision=0",
    "",
]
for key, fades, bar, stat in ELEMENTS:
    ini += ["[%s]" % key, "fX=0", "fY=0", "fScale=1.00", "fLength=1.00", "fHeight=1.00", "bHide=0"]
    if fades:
        ini.append("bAlwaysVisible=0")
    ini.append("sMoveWith=")
    if bar:
        ini.append("; Fill from: 0 = the game's own, 1 = left, 2 = centre, 3 = right - the side the filled part is anchored to.")
        ini.append("iFill=0")
    if stat:
        ini.append("; Length follows the resource: 1 = the bar's length grows with your maximum; it is 1.00x long at fPointsPerLength points.")
        ini += ["bLinkLength=0", "fPointsPerLength=100", "; Grows toward: 0 = both sides (about the centre), 1 = the right (anchored left), 2 = the left (anchored right).", "iGrow=0"]
    ini.append("")
ini += ["[Group]", "; Combined widgets: the elements (section names, comma-separated) that move as one on the shared sliders, and that shared offset.", "sMembers=", "fX=0", "fY=0", ""]
ini += ["[Log]", "; 0 = trace ... 6 = off. Shipped at 2 (info).", "uLogLevel=2", ""]
ini_path = os.path.join(REPO, r"dist\OblivionRemastered\Binaries\Win64\OBSE\Plugins\HUDPositionManager.ini")
with open(ini_path, "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(ini))
print("INI ->", ini_path)
